[package]
name = "redb_model"
authors = ["Christopher Edward Dawn"]
version = "0.10.0"
edition = "2021"
description = "Redb model derive macro and DTO type conversion"
readme = "README.md"
repository = "https://github.com/cedtwo/redb_model.git"
license = "MIT OR Apache-2.0"
keywords = ["redb", "model", "schema"]
categories = ["rust-patterns"]

[dependencies]
redb = "2.1"

[dependencies._derive]
version = "0.11.0"
package = "redb_model_derive"
path = "./redb_model_derive"
default-features = false

[dependencies._trait]
version = "0.8.0"
package = "redb_model_trait"
path = "./redb_model_trait"
default-features = false

[features]
uuid = ["_derive/uuid"]
secrecy = ["_derive/secrecy"]

[dev-dependencies]
uuid = "1.11.0"
secrecy = "0.10.3"
